global:
  timezone: Europe/Zurich
  timezonePath: /etc/localtime
  springDebug: false
  namespace: spring-6-icecold-micro-service

replicaCount: 1

image:
  # Those values are set by Maven filtering
  # and will be replaced with a valid version number during the build process.
  registry: @docker.repo@
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 10
  readiness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

kafka:
  serviceFQDN: "spring-6-icecold-micro-service-kafka.spring-6-icecold-micro-service.svc.cluster.local"
  port: 9092
  clientPort: 29092

ingress:
  enabled: false
